# Generated by Django 5.1.1 on 2024-10-07 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('alive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_limit', models.CharField(default=5, max_length=55)),
                ('aswang_limit', models.CharField(default=1, max_length=10)),
                ('room_code', models.CharField(max_length=8, unique=True)),
                ('room_state', models.CharField(choices=[('LOBBY', 'lobby'), ('IN GAME', 'IN GAME')], default=('LOBBY', 'lobby'), max_length=255, null=True)),
                ('has_started', models.BooleanField(default=False)),
                ('has_ended', models.BooleanField(default=False)),
                ('completed', models.DateField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.player')),
                ('players', models.ManyToManyField(related_name='players', to='game.player')),
                ('winners', models.ManyToManyField(blank=True, related_name='winners', to='game.player')),
            ],
        ),
    ]
