# Generated by Django 5.1.1 on 2024-10-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_player_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_protected',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
