# Generated by Django 5.1.1 on 2024-10-08 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_player_is_protected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='is_protected',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
