# Generated by Django 5.1.1 on 2024-10-08 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_player_is_protected'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='in_game',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
