# Generated by Django 5.1.1 on 2024-10-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_player_in_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='skip_turn',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
