# Generated by Django 5.1.1 on 2024-10-10 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_game_cycle_game_day_count_game_night_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_phase',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
