# Generated by Django 5.1.1 on 2024-10-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_game_game_phase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='day_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='night_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
