# Generated by Django 5.1.1 on 2024-10-12 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_player_eliminated_from_game_player_votes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='voted_for',
        ),
        migrations.AddField(
            model_name='vote',
            name='vote_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voted_target', to='game.player'),
        ),
    ]
