# Generated by Django 5.1.1 on 2024-10-12 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_remove_vote_voted_for_vote_vote_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='vote_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vote_target', to='game.player'),
        ),
    ]
