# Generated by Django 5.1.1 on 2024-10-12 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_alter_vote_vote_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_with_vote', to='game.game'),
        ),
    ]
