# Generated by Django 5.1.1 on 2024-10-12 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_alter_vote_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='game',
            field=models.ManyToManyField(null=True, related_name='games', to='game.game'),
        ),
    ]
