# Generated by Django 5.1.1 on 2024-10-13 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_alter_player_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='votes',
        ),
        migrations.AddField(
            model_name='player',
            name='vote_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voted_player', to='game.player'),
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
