# Generated by Django 5.1.1 on 2024-10-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_remove_player_votes_player_vote_target_delete_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='winners',
        ),
        migrations.AddField(
            model_name='game',
            name='winners',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
