# Generated by Django 5.1.1 on 2024-10-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_remove_game_winners_game_winners'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='night_skip',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
