# Generated by Django 5.1.1 on 2024-10-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_player_night_skip'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='exexcute',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
