# Generated by Django 5.1.1 on 2024-10-16 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_player_exexcute'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='exexcute',
            new_name='execute',
        ),
    ]
