# Generated by Django 5.1.1 on 2024-10-16 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_rename_exexcute_player_execute'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='night_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_of_the_night', to='game.player'),
        ),
    ]
