# Generated by Django 5.1.1 on 2024-10-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_player_night_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='eliminated_on_night',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='revived_on_night',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
