# Generated by Django 5.1.1 on 2024-10-18 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0024_alter_player_night_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='aswang_limit',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='game',
            name='room_limit',
            field=models.IntegerField(default=5),
        ),
    ]
