# Generated by Django 5.1.1 on 2024-10-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0025_alter_game_aswang_limit_alter_game_room_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='in_game',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='player',
            name='username',
            field=models.CharField(blank=True, default='', max_length=255, unique=True),
        ),
    ]
