# Generated by Django 5.1.1 on 2024-10-19 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0026_alter_player_in_game_alter_player_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='in_game',
            field=models.BooleanField(blank=True, default=False, max_length=255),
        ),
    ]
