# Generated by Django 5.1.1 on 2024-10-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0028_player_in_lobby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='in_game',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
