# Generated by Django 5.1.1 on 2024-10-19 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0029_alter_player_in_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='time_since_last_game',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
