# Generated by Django 5.1.1 on 2024-10-21 06:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0030_player_time_since_last_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='time_since_last_game',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
