# Generated by Django 5.1.1 on 2024-10-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0032_alter_player_time_since_last_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='time_since_last_game',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
