# Generated by Django 5.1.1 on 2024-10-23 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0035_alter_player_time_since_last_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='execute',
        ),
        migrations.AddField(
            model_name='player',
            name='can_execute',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
