# Generated by Django 5.1.1 on 2024-10-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0036_remove_player_execute_player_can_execute'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='turn_done',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
