# Generated by Django 5.1.1 on 2024-10-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0037_player_turn_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='cycle',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
