# Generated by Django 5.1.1 on 2024-10-31 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0038_alter_game_cycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='avatar',
            field=models.CharField(blank=True, default='taumbayan_tatay', max_length=255, null=True),
        ),
    ]
